# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]

name: lint-changed-files

jobs:
  lint-changed-files:
    uses: easystats/workflows/.github/workflows/lint-changed-files.yaml@main
