# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

on:
  push:
    branches: [main, master]
    paths: README.Rmd
  pull_request:
    branches: [main, master]
    paths: README.Rmd
  schedule:  # run every day
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

name: render-README

jobs:
  render-README:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

     - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
              deps::.
              any::sessioninfo
              any::deepdep
              any::miniCRAN
              any::cranlogs
              any::tidyverse
              any::zoo

      - name: Render README file
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
